### ISSUE TITLE
What's the parameter for the webhook?

### ISSUE THREAD

**Issue by Calius** [OXID-eSales/paypal-module#30]
Tried to integrate it in a sandbox environmten, but there's no info what the parameter for the webhook is. For the deprecated PayPalPlus integration it's: cl=payppaypalpluswebhook

**Comment by mariolorenz** [comment]
Hello Calius, the best way is, that you run the integration-process (clicking the blue-button on the config-page). During the Integration, the Credentials and the Webhook-ID will be created. Also the Access to the Services Pay Upon Invoice and CreditCard will be granted.

But by the way here the controller: cl=oscpaypalwebhook
