### ISSUE TITLE
v1.1.4 - Class 'OxidSolutionCatalysts\PayPal\Service\Registry' not found

### ISSUE THREAD

**Issue by gaertnermarkus** [OXID-eSales/paypal-module#41]
OXID Logger.ERROR: Class 'OxidSolutionCatalysts\PayPal\Service\Registry' not found ["[object] (Error(code: 0): Class 'OxidSolutionCatalysts\\PayPal\\Service\\Registry' not found at /home/elegltyp/dev.elektroversand-schmidt.de/vendor/oxid-solution-catalysts/paypal-module/src/Service/ModuleSettings.php:373)\n[stacktrace]\n
#0 /home/elegltyp/dev.elektroversand-schmidt.de/vendor/oxid-solution-catalysts/paypal-module/src/Core/ViewConfig.php(71): OxidSolutionCatalysts\\PayPal\\Service\\ModuleSettings->isPayPalCheckoutExpressPaymentEnabled()

**Comment by mariolorenz** [comment]
Thanks for the note. Please checkout v1.1.4 again. I´ve add the missing Class.
