### ISSUE TITLE
Error on module activation ^1.0.0 / CE 6.1.6 / PHP 7.1

### ISSUE THREAD

**Issue by tabsl** [OXID-eSales/paypal-module#42]
error on module activation

`[2022-07-11 14:50:40] OXID Logger.ERROR: Class 'OxidEsales\EshopCommunity\Internal\Container\ContainerFactory' not found ["[object] (Error(code: 0): Class 'OxidEsales\\EshopCommunity\\Internal\\Container\\ContainerFactory' not found at /var/www/html/vendor/oxid-solution-catalysts/paypal-module/src/Core/Events/Events.php:62)\n[stacktrace]\n#0 /var/www/html/vendor/oxid-solution-catalysts/paypal-module/src/Core/Events/Events.php(31): OxidSolutionCatalysts\\PayPal\\Core\\Events\\Events::addStaticContents()\n#1 [internal function]: OxidSolutionCatalysts\\PayPal\\Core\\Events\\Events::onActivate()\n#2 /var/www/html/vendor/oxid-esales/oxideshop-ce/source/Core/Module/ModuleInstaller.php(577): call_user_func('\\\\OxidSolutionCa...')\n#3 /var/www/html/vendor/oxid-esales/oxideshop-ce/source/Core/Module/ModuleInstaller.php(127): OxidEsales\\EshopCommunity\\Core\\Module\\ModuleInstaller->_callEvent('onActivate', 'osc_paypal')\n#4 /var/www/html/vendor/oxid-esales/oxideshop-ce/source/Application/Controller/Admin/ModuleMain.php(83): OxidEsales\\EshopCommunity\\Core\\Module\\ModuleInstaller->activate(Object(OxidEsales\\Eshop\\Core\\Module\\Module))\n#5 /var/www/html/vendor/oxid-esales/oxideshop-ce/source/Core/Controller/BaseController.php(524): OxidEsales\\EshopCommunity\\Application\\Controller\\Admin\\ModuleMain->activateModule()\n#6 /var/www/html/source/modules/ProudSourcing/psCache/Core/ShopControl.php(118): OxidEsales\\EshopCommunity\\Core\\Controller\\BaseController->executeFunction('activateModule')\n#7 /var/www/html/vendor/oxid-esales/oxideshop-ce/source/Core/ShopControl.php(137): ProudSourcing\\psCache\\Core\\ShopControl->_process('OxidEsales\\\\Esho...', 'activateModule', NULL, NULL)\n#8 /var/www/html/vendor/oxid-esales/oxideshop-ce/source/Core/Oxid.php(26): OxidEsales\\EshopCommunity\\Core\\ShopControl->start()\n#9 /var/www/html/source/index.php(15): OxidEsales\\EshopCommunity\\Core\\Oxid::run()\n#10 /var/www/html/source/admin/index.php(11): require_once('/var/www/html/s...')\n#11 {main}\n"] []
`

**Comment by mariolorenz** [comment]
@tabsl : Did you try it again? It works fine in v1.1.4...

**Comment by tabsl** [comment]
> @tabsl : Did you try it again? It works fine in v1.1.4...

yes, works, thx
