### ISSUE TITLE
Feature request: oxid order number in description

### ISSUE THREAD

**Issue by metropolisdrachen** [OXID-eSales/paypal-module#43]
Currently there is only OSC_PAYPAL_DESCRIPTION from the language files and the $shopName  transmitted as description for Paypal.
Can this description be extended by the oxid shop order number?

I tried already some options, but as i am not a programmer, it did not worked.

**Comment by mariolorenz** [comment]
@metropolisdrachen: Unfortunately no, PayPal doesn't make it easy for us. When the order is "created" at PayPal, the order number is not even generated in OXID. We have to work with a dummy order here, which is then updated several times during the checkout. But I'll include that there is a method to override the order description.

**Comment by mariolorenz** [comment]
Yes it is. I`ve explain it in the forum. Maybe the capture-transactionid (submited again with v2.1.5, v1.1.5) will help you with the  assignment of the OXID orders in PayPal ...
