### ISSUE TITLE
Transaction ID in database is not the same transaction ID as listed in the Paypal transactions

### ISSUE THREAD

**Issue by metropolisdrachen** [OXID-eSales/paypal-module#44]
The transaction ID in the table oscpaypal_order, column OXPAYPALORDERID and the table oxorder, column OXTRANSID is not the same as the transaction ID which is shown on the Paypal page and in the payment confirmation mails from Paypal.

For example, stored in the database is 2YD40639T891***** and the ID shown on the Paypal website and in the payment confirmation mails is 9UC46578HC50*****

In the oxid shop backend in the tab Orders->Paypal Checkout the same number as on the Paypal website and the payment confirmation mails 9UC46578HC50***** is shown, but only there.
In the database you would only find 2YD40639T891***** and not 9UC46578HC50*****

Is there any way to get the ID which is shown at the Paypal website and the confirmation mails in a column of the table oxorder?
We are using this ID to match payments from PayPal with our invoices for our accounting.

At the current state we only have the e-mail address which can be compared between Paypal and our invoicing database.

**Comment by mariolorenz** [comment]
Hello @metropolisdrachen: The PayPalOrderId and the transId are the same. This ID is the global central ID for the order. A Order can have more than one transaction (Part-Transactions, Returns ...). And all transactions have an own transactionID. There is a possibility to list this transactions with the IDs. You can see it live in the backend (Admin > Order > PayPalCheckout Tab).
Is it possible for you, to call PHP-Code in your Connector between OXID and your Invoicing Database? Then you´ve actual a chance ...

**Comment by metropolisdrachen** [comment]
Hello @mariolorenz 
Thank you for your answer (and also for the answer in the Oxid Forum) 
The OSC Ware software has a connector.php in a folder, but as i am not a programmer, i don´t know how to do that,
also it is not update secure, when i modify this connector.php

Bu i can ask the software developers , if they can modify the code, so that the first ID of the intial payment will be transmitted to the invoicing software.

Kind regards,
Michael

**Comment by mariolorenz** [comment]
We will  take the first capture-transaction-id and write it to the oxtransid-field. This helps in 90%. Sometimes an Order has a lot of transaction-ids. We list this transactions in the backend on the fly via API. But we do not save it to the DB (only the first).
You will get it in v2.1.5/v1.1.5
