### ISSUE TITLE
Bug? When refunding amounts, the refunds only will be shown after reloading the checkout tab

### ISSUE THREAD

**Issue by metropolisdrachen** [OXID-eSales/paypal-module#45]
One thing that i have noticed when refunding amounts with the new Paypal Checkout module is, that the
page is not refreshing and showing the refunded amount after clicking on the "Refund" button.
The frame only scrolls to the top but shows the same state as before the refund.

![refund1](https://user-images.githubusercontent.com/98336374/179948661-05b0ebd6-148c-44a8-8a72-013a1f6c3333.jpg)

If you click on the "Paypal Checkout" tab again or leave this tab and go back to it, then the refund is visible:

![refund-2](https://user-images.githubusercontent.com/98336374/179948907-eb372efb-5acf-4e80-ae52-4e07c8035d17.jpg)

Also noticed: the Resulting payment amount does not update and is always showing 0,00 EUR

On the old Paypal module, the refund was shown immediatley after refunding an amount.

**Comment by mariolorenz** [comment]
Thank you for the note. I´ve doublecheck the behavior and found a solution. The fix will come into the next release v2.1.5/v1.1.5
