### ISSUE TITLE
orders are not marked paid correctly

### ISSUE THREAD

**Issue by weberdigital** [OXID-eSales/paypal-module#49]
in Version 2.1.6 ACDC AND PUI orders will not be marked as paid onymore
Can you fix that?

**Comment by prof2** [comment]
1. Same issue with version 1.1.6 ACDC.
2. PP-Express still not working properly, so had to deactive it.
It seems to me, live transactions got problems that may not occur on sandbox tests.

**Comment by mariolorenz** [comment]
It will be fixed in v2.1.7 / v.1.1.7 We move this task in our internal tracking-system ...
