### ISSUE TITLE
We get an error when clicking on the paypal button

### ISSUE THREAD

**Issue by markom-werbeagentur** [OXID-eSales/paypal-module#51]
Object { err: "Expected an order id to be passed\nf/</<@https://www.paypal.com/smart/buttons?sdkVersion=5.0.330&style.layout=vertical&style.color=gold&style.shape=rect&style.tagline=false&style.menuPlacement=below&components.0=buttons&components.1=messages&locale.country=US&locale.lang=en&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVdFQWZzVVI1cHhxbGxXZm1aTF9vRTRGTUQzRTlMSnBJYVhnOXRuc0VNaF94SF9QMnQ5Mk42QTFQV2FjUnc3dzNKSjZjbEYyZ0R6LTF5NE8maW50ZWdyYXRpb24tZGF0ZT0yMDIwLTA3LTI5JmludGVudD1jYXB0dXJlJmNvbW1pdD1mYWxzZSZjdXJyZW5jeT1FVVImY29tcG9uZW50cz1tZXNzYWdlcyUyQ2J1dHRvbnMmZGlzYWJsZS1mdW5kaW5nPXNlcGElMkNiYW5jb250YWN0JTJDYmxpayUyQ2VwcyUyQ2dpcm9wYXklMkNpZGVhbCUyQ21lcmNhZG9wYWdvJTJDbXliYW5rJTJDcDI0JTJDc29mb3J0JTJDdmVubW8mZW5hYmxlLWZ1bmRpbmc9Y2FyZCIsImF0dHJzIjp7ImRhdGEtdWlkIjoidWlkX2l6cnhqeXNhb3pueHBpcWlzb29lY3BsZ2F5Y2xubSJ9fQ&clientID=XXXXXXXX&sdkCorrelationID=f98669778f1c7&storageID=uid_0876ea3562_mte6ntu6ntq&s…", timestamp: "1662120296995", referer: "www.paypal.com", sdkCorrelationID: "f98669778f1c7", sessionID: "uid_e44bb8ac34_mte6ntu6ntq", clientID: "XXXXXXXX", env: "production", buttonSessionID: "uid_da2bf35f80_mti6mdq6ndy", buttonCorrelationID: "f48090126ddd6", time: "1662120296995", … }

**Comment by mariolorenz** [comment]
If you could reproduce it every time, please wrote an bugreport with steps for reproducing to: https://bugs.oxid-esales.com/
